const nfts = [
    { 
        title: "a forest",
        desc: "Warm textural layers evoking solar energy and molten light.", 
        longDesc: "Full long-form description for 'a forest' goes here.",
        date: "Dec 2025", 
        dims: "6000 x 6000px",
        aspectRatio: "1/1",
        file: "images/full/a-forest-3.jpg",
        price: "NFT listing",
        quote: "Digital art is a medium that asks the same old question every true artwork must answer: does it tremble with truth, or merely glitter with novelty?",
        themes: "This piece explores the dynamic tension between action and inaction, capturing the visceral response to perceived threats through abstract forms and vibrant colors.",
        analysis: "Under the surface the canvas is alive with color interactions that suggest movement and emotional intensity. The juxtaposition of sharp angles and fluid shapes creates a sense of conflict and resolution, mirroring the human experience of confronting fears and desires.",
        collector: "First edition NFT; RVL signature; part of the 2025 series.",
        series: "this is a landscape based work within the larger 2025 series exploring elemental forces through abstract digital collages.",
        artistNotes: "Russell's ability to convey such raw emotion through abstraction is truly remarkable. 'Golden Desire' resonates deeply, evoking a primal response that is both captivating and thought-provoking. - Art Critic Magazine",
        keywords: ["digital art", "landscape", "abstract", "collage", "2025 series"]
    },
    { 
        title: "Blue Redux",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "6000 x 6000px",
        aspectRatio: "1/1",
        file: "images/full/Blue-Redux-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "blue"]
    },
    { 
        title: "moving on",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "6000 x 6000px",
        aspectRatio: "1/1",
        file: "images/full/moving-on-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    },
    { 
        title: "Cloud background",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "6000 x 6000px",
        aspectRatio: "1/1",
        file: "images/full/Cloud-background-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "landscape"]
    },
    { 
        title: "a quiet escape",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "6000 x 6000px",
        aspectRatio: "1/1",
        file: "images/full/a-quiet-escape-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "landscape"]
    },
    { 
        title: "Cowboy in the woods",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "6000 x 6000px",
        aspectRatio: "1/1",
        file: "images/full/Cowboy-in-the-woods-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "landscape"]
    },
    { 
        title: "Cowgirl in the sand",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "6000 x 6000px",
        aspectRatio: "1/1",
        file: "images/full/Cowgirl-in-the-sand-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "landscape"]
    },
    { 
        title: "fight or flight",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2025", 
        dims: "6000 x 6000px",
        aspectRatio: "1/1",
        file: "images/full/Fight-or-flight-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2025 series.",
        series: "Part of the 2025 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    },
    { 
        title: "Golden Desire",
        desc: "Fight or flight is an abstract composition dominated by warm, earthy tones - gold, ochre, and burnt orange. The background has a textured, painterly feel, with soft gradients and layered brushstrokes that give it depth and warmth, glowing like heated metal. In the foreground, sweeping strokes of saturated yellow and vivid red create a dynamic focal point. These bold, curved shapes move across the canvas - like a flame, swooping bird or a flowing ribbon. The red stroke adds intensity and contrast, standing out sharply against the golden backdrop. The painting conveys energy and warmth with its swirling forms and rich, fiery colors.", 
        date: "Dec 2025", 
        dims: "6000 x 6000px",
        aspectRatio: "1/1",
        file: "images/full/Golden-Desire-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This piece explores the dynamic tension between action and inaction, capturing the visceral response to perceived threats through abstract forms and vibrant colors.",
        analysis: "Under the surface the canvas is alive with color interactions that suggest movement and emotional intensity.",
        collector: "First edition NFT; RVL signature; part of the 2025 series.",
        series: "Part of the 2025 abstract series exploring elemental forces.",
        artistNotes: "Russell's ability to convey such raw emotion through abstraction is truly remarkable. 'Golden Desire' resonates deeply, evoking a primal response that is both captivating and thought-provoking. - Art Critic Magazine",
        keywords: ["digital art", "abstract", "warm tones", "energy", "2025 series"]
    },
    { 
        title: "in the land of green and red",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "3840 x 2160px",
        aspectRatio: "16/9",
        file: "images/full/in-the-land-of-green-and-red-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "landscape"]
    },
    { 
        title: "in the land of indecisions",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "3840 x 2160",
        aspectRatio: "16/9",
        file: "images/full/in-the-land-of-indecisions-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "landscape"]
    },
    { 
        title: "in the land of make believe",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "3840 x 2160px",
        aspectRatio: "16/9",
        file: "images/full/in-the-land-of-make-believe-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "landscape"]
    },
    { 
        title: "in the land of pink and gray",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "3840 x 2160px",
        aspectRatio: "16/9",
        file: "images/full/in-the-land-of-pink-and-grey-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "landscape"]
    },
    { 
        title: "Like Father, Like Son",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "3840 x 2160px",
        aspectRatio: "16/9",
        file: "images/full/Like-Father-Like-Son-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    },
    { 
        title: "The dollar is our king",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "3840 x 2160px",
        aspectRatio: "16/9",
        file: "images/full/The-dollar-is-our-king-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    },
    { 
        title: "Kline again",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "3849 x 2399px",
        aspectRatio: "8/5",
        file: "images/full/Kline-again-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    },
    { 
        title: "vulture values",
        desc: "Organic, painterly textures blended with sharp digital artifacts.", 
        date: "Dec 2025", 
        dims: "3850 x 2400px",
        aspectRatio: "8/5",
        file: "images/full/vulture-values-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This piece explores the dynamic tension between action and inaction, capturing the visceral response to perceived threats through abstract forms and vibrant colors.",
        analysis: "Organic painterly textures contrast with sharp digital artifacts creating tension.",
        collector: "First edition NFT; RVL signature; part of the 2025 series.",
        series: "Part of the 2025 abstract series.",
        artistNotes: "A commentary on modern values through abstract digital collage.",
        keywords: ["digital art", "abstract", "texture", "contrast", "2025 series"]
    },
    { 
        title: "All American",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "3850 x 2400px",
        aspectRatio: "8/5",
        file: "images/full/All-American-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    },
    { 
        title: "by my side",
        desc: "High-energy gestural strokes with a complex digital overlay.", 
        date: "Dec 2024", 
        dims: "7280 x 5200px",
        aspectRatio: "7/5",
        file: "images/full/by-my-side-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This piece explores the dynamic tension between action and inaction, capturing the visceral response to perceived threats through abstract forms and vibrant colors.",
        analysis: "High-energy gestural strokes create movement and intensity across the canvas.",
        collector: "First edition NFT; RVL signature; part of the 2024 series.",
        series: "Part of the 2024 abstract series exploring emotional landscapes.",
        artistNotes: "A powerful exploration of connection and presence through digital abstraction.",
        keywords: ["digital art", "abstract", "gestural", "energy", "2024 series"]
    },
    { 
        title: "everything you want me to",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "7280 x 5200",
        aspectRatio: "7/5",
        file: "images/full/everything-you-want-me-to-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    },
    { 
        title: "ease my worried mind",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "2732 x 2048px",
        aspectRatio: "4/3",
        file: "images/full/ease-my-worried-mind-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    },
    { 
        title: "Thunderhead Melody",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "7280 x 5200px",
        aspectRatio: "7/5",
        file: "images/full/Thunderhead-Melody-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract", "landscape"]
    },
    { 
        title: "Red room",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "4200 x 3000px",
        aspectRatio: "7/5",
        file: "images/full/Red-room-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    },
    { 
        title: "Make room",
        desc: "This section provides a concise visual description of the artwork for viewers encountering it for the first time. Describe the dominant colors, primary shapes, compositional layout, and overall aesthetic impression. Mention key visual elements like textures, patterns, or distinctive features that immediately catch the eye. Keep the tone accessible and engaging, helping viewers understand what they are looking at before diving into deeper analysis. Focus on observable qualities rather than interpretation, creating a clear mental image of the piece through words.", 
        date: "Dec 2023", 
        dims: "4200 x 3000px",
        aspectRatio: "7/5",
        file: "images/full/Make-room-3.jpg",
        price: "NFT listing",
        quote: "Placeholder quote text for this artwork will be replaced with actual content from uploaded file later.",
        themes: "This section explores the conceptual themes, emotional resonance, and symbolic meanings within the artwork. Consider what ideas, feelings, or narratives the piece conveys through its visual elements, color choices, and compositional structure. Discuss the underlying concepts that give the work deeper significance beyond its surface aesthetics.",
        analysis: "This section provides visual analysis of the artwork's composition, technique, and formal qualities. Examine color palette interactions, spatial relationships, textural elements, and how various components work together. Discuss the technical execution, layering methods, and distinctive stylistic choices that define the piece's visual character and aesthetic impact.",
        collector: "First edition NFT; RVL signature; part of the 2023 series.",
        series: "Part of the 2023 abstract series.",
        artistNotes: "This section shares the artist's perspective on the creative process, inspiration, and intentions behind the work. Include thoughts on what motivated the piece, challenges encountered during creation, breakthrough moments, or personal reflections. Consider discussing influences, experimental techniques used, or what the artist hopes viewers will experience when engaging with the artwork.",
        keywords: ["digital art", "abstract"]
    }
];


