const nfts = [
   { 
        title: "Golden Desire",
        desc: "Fight or flight is an abstract composition dominated by warm, earthy tones - gold, ochre, and burnt orange. The background has a textured, painterly feel, with soft gradients and layered brushstrokes that give it depth and warmth, glowing like heated metal. In the foreground, sweeping strokes of saturated yellow and vivid red create a dynamic focal point. These bold, curved shapes move across the canvas - like a flame, swooping bird or a flowing ribbon. The red stroke adds intensity and contrast, standing out sharply against the golden backdrop. The painting conveys energy and warmth with its swirling forms and rich, fiery colors.", 
        date: "Dec 2025", 
        dims: "6000 x 6000px", 
        file: "images/full/Golden-Desire-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "This piece explores the dynamic tension between action and inaction, capturing the visceral response to perceived threats through abstract forms and vibrant colors.",
        testi: "Russell's ability to convey such raw emotion through abstraction is truly remarkable. 'Golden Desire' resonates deeply, evoking a primal response that is both captivating and thought-provoking. - Art Critic Magazine",
    },
    { 
        title: "a forest",
        desc: "Warm textural layers evoking solar energy and molten light.", 
        date: "Dec 2025", 
        dims: "6000 x 6000px", 
        file: "images/full/a-forest-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "This piece explores the dynamic tension between action and inaction, capturing the visceral response to perceived threats through abstract forms and vibrant colors.",
        testi: "Russell's ability to convey such raw emotion through abstraction is truly remarkable. 'Golden Desire' resonates deeply, evoking a primal response that is both captivating and thought-provoking. - Art Critic Magazine",
    },
    { 
        title: "by my side",
        desc: "High-energy gestural strokes with a complex digital overlay.", 
        date: "Dec 2024", 
        dims: "3840 x 2160", 
        file: "images/full/by-my-side-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "This piece explores the dynamic tension between action and inaction, capturing the visceral response to perceived threats through abstract forms and vibrant colors.",
        testi: "Russell's ability to convey such raw emotion through abstraction is truly remarkable. 'Golden Desire' resonates deeply, evoking a primal response that is both captivating and thought-provoking. - Art Critic Magazine",
    },
    { 
        title: "vulture values",
        desc: "Organic, painterly textures blended with sharp digital artifacts.", 
        date: "Dec 2025", 
        dims: "3840 x 2160", 
        file: "images/full/vulture-values-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "This piece explores the dynamic tension between action and inaction, capturing the visceral response to perceived threats through abstract forms and vibrant colors.",
        testi: "Russell's ability to convey such raw emotion through abstraction is truly remarkable. 'Golden Desire' resonates deeply, evoking a primal response that is both captivating and thought-provoking. - Art Critic Magazine",
    },
    { 
        title: "a quiet escape",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/a-quiet-escape-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "Blue Redux",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/Blue-Redux-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "in the land of pink and gray",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/in-the-land-of-pink-and-grey-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "everything you want me to",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/everything-you-want-me-to-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "Cloud background",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/Cloud-background-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "Cowboy in the woods",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/Cowboy-in-the-woods-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "Cowgirl in the sand",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/Cowgirl-in-the-sand-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "in the land of indecisions",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/in-the-land-of-indecisions-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "Kline again",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/Kline-again-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "fight or flight",
        desc: "ctcs.", 
        date: "Dec 2025", 
        dims: "6000 x 6000px", 
        file: "images/full/Fight-or-flight-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "Thunderhead Melody",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/Thunderhead-Melody-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "ease my worried mind",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/ease-my-worried-mind-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "running all day",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/running-all-day-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "Like Father, Like Son",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/Like-Father-Like-Son-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "The dollar is our king",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/The-dollar-is-our-king-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "Red room",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/Red-room-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "in the land of green and red",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/in-the-land-of-green-and-red-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "moving on",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/moving-on-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "in the land of make believe",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/in-the-land-of-make-believe-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
    { 
        title: "All American",
        desc: "ctcs.", 
        date: "Dec 2023", 
        dims: "3840 x 2160", 
        file: "images/full/All-American-3.jpg",
        price: "Minted NFT - 2.5 ETH",
        notes: "ctc.",
        testi: "ctc",
    },
];